#!/bin/sh


BUILDTYPE=RELWITHDEBINFO
if [ "$1" = "debug" ] ; then 
    BUILDTYPE=DEBUG
fi
if [ "$1" = "nodebug" ] ; then
    BUILDTYPE=RELEASE
fi

NPROC=`which nproc`
if [ "$NPROC" = "" ] ; then
	PROCS=2
else
	PROCS=`$NPROC`
fi
	
	
mkdir -p ./data
mkdir -p ./secure_data
mkdir -p ./log
mkdir -p ./run
mkdir -p ./.build

if [ -f update_version ] ; then
	GIT=`which git`
	VER=`$GIT describe --tags`
	cp update_version ./version.h
	echo " \"$VER\"" >> ./version.h
fi

cmake -DCMAKE_BUILD_TYPE=$BUILDTYPE -B.build -S .
echo "Building in $PROCS thread(s)"
(cd .build;make all -j$PROCS)
echo Done >&2