#!/bin/sh

BUILDTYPE=RELWITHDEBINFO
if [ "$1" = "debug" ] ; then 
    BUILDTYPE=DEBUG
fi

NPROC=`which nproc`
if [ "$NPROC" = "" ] ; then
	PROCS=2
else
	PROCS=`$NPROC`
fi
	
mkdir -p ./data
mkdir -p ./secure_data
mkdir -p ./log
mkdir -p ./run
cmake -DCMAKE_BUILD_TYPE=$BUILDTYPE .
make all -j `nproc`
