#!/bin/bash

git -c user.name="Update" -c user.email="update@localhost.localdomain"  commit -a -m "" --allow-empty-message 

set -e

git pull
git submodule update --init
cmake -DCMAKE_BUILD_TYPE=RELWITHDEBINFO .
make all -j `nproc`
